### ISSUE TITLE
Documents posted on Slack

### ISSUE THREAD

**Issue by DevilPepper** [medgardo/ctp2016#4]
Can you also add documents posted on slack and links to some google docs?

docs/
----syllabus.doc
----section_stuff.xls
----forms_we_were_given
----README.md
--------Link to job opportunity bulletin that was posted
--------Maybe a link to a spreadsheet that has resources that are posted. It would be shared with us and we are responsible for adding to it. Stuff gets lost in Slack conversations.

I was looking for the syllabus. It's not here. I also saw a doc about linked lists shared on Slack. That's not here either. Maybe have a folder for that stuff too and keep this repo up to date. Add contributors that could push these things up if they are coming from scattered sources.

**Comment by greszy** [comment]
I agree. That would be useful.

**Comment by medgardo** [comment]
@SupaStuff @Greszy Thanks for the suggestion. The documents you requested will be split between the docs folder and a Private Shared Folder with the program.
